### PR TITLE
[OPTIONS] Added in chrome options UI with themes and custom bookmark…

### LINKED ISSUE #58: Build options UI
https://developer.chrome.com/extensions/optionsV2

### PR DESCRIPTION
**Pull request by briangonzalez**
This PR fixes #58, #62, #54

### CODE REVIEW

**Comment by briangonzalez** [comment]
@iklsr @sifxtreme Mind giving this one a shot?

https://github.com/eggplanetio/tidytab/releases/tag/2.8.0-beta.1

**Comment by iKlsR** [comment]
The list of folders was the thing I was trying to escape. Hear me out, I'm somewhat addicted to procrastinating and bookmarks *haha...*. I have over 31k meticulously curated across 400 folders from 2007 so the picker gets a bit unwieldy for me so the search is a nice touch and it shouldn't affect the average user that just wants some tab estate and a little memory back. Never used chrome `options` before so going back to extensions tab to configure was a bit weird. Overall everything works, great! 

Gripes
- Dark theme is not actually dark, just a hideous (sorry) blast of purple, maybe make that a bit more clear in the name, trivial.
- Color scheme is a bit mismatched, the purple and blue lettering clashes with the darker themes IMHO
- I like the new icon tho the outline of the brush could be a bit thicker? and the extension TAB doesn't seem to use the same one as that on the extension BAR, also trivial, your preference

Bugs
- When searching for a folder to set as the ext. folder it wants to use the actual URLs as a destination as opposed to DIRS only
- After searching, if I scroll the search text is discarded and I get the long list again

**Comment by briangonzalez** [comment]
Thanks so much for the feedback! I totally hear what you're saying about users like yourself with a ton of bookmarks. You found a bug which made it more unwieldy than it should have been due to the fact that we were using folders _and_ bookmarks, not just folders. I have a fix on the way that should mitigate.

> Dark theme is not actually dark, just a hideous (sorry) blast of purple, maybe make that a bit more clear in the name, trivial.

We'll clean up the look & feel in a later release.

> I like the new icon tho the outline of the brush could be a bit thicker?

We can make this more attractive later, too.

> When searching for a folder to set as the ext. folder it wants to use the actual URLs as a destination as opposed to DIRS only

Good catch! I am going to push a fix for this now.

> After searching, if I scroll down the search text is discarded and I get the long list again, search should be persistent

Can you post a video of this? I will attach what I see.

tidytab-selection

**Comment by briangonzalez** [comment]
@iKlsR I've gone ahead and pushed `2.8.0-beta.2` with your bug fixes. You can find it attached to the release below.

Thanks again!

https://github.com/eggplanetio/tidytab/releases/tag/2.8.0-beta

**Comment by briangonzalez** [comment]
2.8.0 has been published and should be live here shortly :)

**Comment by iKlsR** [comment]
@briangonzalez Issue I mentioned

)

**Pull request merged**
