### PR TITLE
Group by date & eslint

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by briangonzalez** [comment]
@iKlsR 

Mind giving this release a shot? https://github.com/eggplanetio/tidytab/releases/tag/2.13.0

It'll allow a user to group their tab groups by date. See gif below.


screen capture on 2017-05-21 at 08-25-46

**Comment by iKlsR** [comment]
@briangonzalez Sure, give me a few hours tho. Have some chores to take care of.

**Comment by iKlsR** [comment]
@briangonzalez Windows picking up the release as malware and won't let me dload it. Pulled the pr and built, looks good here.

**Comment by briangonzalez** [comment]
Great! Thanks dude. Going to release later tonight.

**Pull request merged**
