### PR TITLE
[Option] Silently reject dups (Fixes #49)

### LINKED ISSUE #49: Silently reject duplicates
A toggle to reject duplicates silently would be nice OR highlight them in a different color that signifies a dupe, <strike>current behavior is to split them into several tabs, not sure if this was a workaround of sorts. Also, is this behavior related to or a side product of https://github.com/eggplanetio/tidytab/commit/2c180f038642f5421dce633f774efe4980af643d?</strike> 

Struck out text is probably related to #48

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by briangonzalez** [comment]
@iKlsR Mind taking this one for a spin?

https://github.com/eggplanetio/tidytab/releases/tag/2.19.0-beta.1

**Comment by iKlsR** [comment]
@briangonzalez Tested, ran against a few dozen bookmarks, instantaneous. There is the existing behaviour of tidying multiple of the same tabs tho but that is fine I guess as this is a post op.

**Comment by briangonzalez** [comment]
Thanks!

> There is the existing behaviour of tidying multiple of the same tabs

Can you explain this one further?

**Comment by iKlsR** [comment]
If I tidy multiple `google.com` tabs they appear as separate entries.

**Comment by briangonzalez** [comment]
Ahhh, ok. We'd need to think about how the UI would look to denote a grouping, right?

**Comment by iKlsR** [comment]
Hmm, not quite. I mean if I tidy 3 of the same tab, I probably don't want to see it 3 times.

**Comment by iKlsR** [comment]
Grouping like tabs sounds interesting tho. Never thought of that but could be useful as a filter option.

**Comment by briangonzalez** [comment]
Ah, I see. I get it now. This is my misunderstanding.

As I see it now, this feature actually consists of two parts, the second part unimplemented:

1. Don't tidy dups which have already been tidied
1. Don't tidy dups which are about to be tidied within the window

**Comment by briangonzalez** [comment]
I can follow up with the second one pretty shortly. Shouldn't be too bad now that I have the base implementation.

**Comment by iKlsR** [comment]
Right, thanks for your hard work.

**Pull request merged**
